### ISSUE TITLE
Openocd Failed

### ISSUE THREAD

**Issue by maxkunes** [enjoy-digital/pcie_injector#1]
C:\Users\user\Desktop\openocd-0.10.0\bin-x64>openocd -f flash_screamer.cfg
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
none separate
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
adapter speed: 10000 kHz
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Error: libusb_open() failed with LIBUSB_ERROR_NOT_FOUND
Error: no device found
Error: unable to open ftdi device with vid 0403, pid 6011, description '*', serial '*' at bus location '*'

flash_screamer.cfg is from the bottom of this page:
http://blog.lambdaconcept.com/doku.php?id=products:pcie_screamer

I have the programmer (http://shop.lambdaconcept.com/home/25-jtagserial-pack.html) plugged into a usb 2.0 slot on my computer.

The programmer shows up as this in device manager:
https://i.imgur.com/lIYHyar.png

Possibly a driver issue?

**Comment by key2** [comment]
https://github.com/ntfreak/openocd

take from here

**Comment by enjoy-digital** [comment]
Closing since sovled.
